### ISSUE TITLE
Contributer

### ISSUE THREAD

**Issue by 123345666777777777777777777777777** [BlacketWare/blacket-hacks#91]
Can I be a contributer.

Thanks

**Comment by 123345666777777777777777777777777** [comment]
@notzastix

**Comment by 123345666777777777777777777777777** [comment]
It was me who traded you

**Comment by notzastix** [comment]
If you know JS and are interested in contributing you can add new scripts / fix or modify current ones, via [pull requests](https://github.com/BlacketWare/blacket-hacks/pulls).
