### ISSUE TITLE
Bug?

### ISSUE THREAD

**Issue by ILuvBlacket** [BlacketWare/blacket-hacks#97]
Sometimes in the console while using SpamOpenBoxes it says "jquery.js:2          POST https://blacket.org/worker/box/openbox.php 502" "jquery.js:2          GET https://blacket.org/worker/trading/checktrading.php 502" or "GET https://blacket.org/worker/user/gettokens.php 502"

**Comment by ILuvBlacket** [comment]
> When it has /checktrading.php, that is nothing related to Spam Open Boxes. For either of the other errors, reload the page and run the script again.



The script worked better after i reloaded it, and i used this script now im 1# on the leaderboard lol, thank you so much for making this script. 

(![image](https://user-images.githubusercontent.com/118382945/202451782-b10c8e26-bbf5-4410-9126-0a89e99f41d9.png))

**Comment by VillainsRule4000** [comment]
> > When it has /checktrading.php, that is nothing related to Spam Open Boxes. For either of the other errors, reload the page and run the script again.
> 
> The script worked better after i reloaded it, and i used this script now im 1# on the leaderboard lol, thank you so much for making this script.
> 
> (![image](https://user-images.githubusercontent.com/118382945/202451782-b10c8e26-bbf5-4410-9126-0a89e99f41d9.png))

the /checktrading.php error is xotic being unable to code
the /getokens.php is also xotic being unable to code
the /openbox.php is you being logged out, since you are sometimes logged out.
